apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ray-head
  labels:
    component: ray
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: PathPrefix(`/`)
    services:
    - kind: Service
      name: {{ .Values.serviceName }}
      namespace: ray
      port: 10001
      scheme: h2c
