apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ray-head
  labels:
    component: ray
spec:
  defaultBackend:
    service:
      name: {{ .Release.Name }}-ray-head
      port:
        number: 10001
