{{- if .Values.rbacEnable }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "kubray-operator.labels" . | indent 4 }}
  name: {{ include "kubray-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name  }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubray-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
