apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  labels:
    control-plane: kuberay-operator
  name: kuberay-operator
spec:
  ports:
    - name: monitoring-port
      port: 8080
      targetPort: 8080
  selector:
    control-plane: kuberay-operator
  type: ClusterIP